config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:index, :show, :destroy] do
    post :follows, to: 'users#follow'
    delete :follows, to: 'users#unfollow'
    post :messages
  end
  resources :cinemas
  resources :movies do
    resources :timetables, except: [:show, :index]
    resources :photos, only: [:index, :update, :destroy]
    post :add_photos, on: :member, to: 'movies#add_photos'
    post :likes, on: :member, to: 'movies#like'
    delete :likes, on: :member, to: 'movies#unlike'
    post :comments, on: :member, to: 'movies#new_comment'
    patch :comments, on: :member, to: 'movies#new_comment'
    delete :comments, on: :member, to: 'movies#delete_comment'
    delete :comment_by_id, on: :member, to: 'movies#delete_comment_by_id'
    delete :timetables_by_cinema, on: :member, to: 'movies#delete_timetables_by_cinema'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  acts_as_messageable required: :body

  acts_as_liker
  acts_as_follower
  acts_as_followable

  has_many :comments

  GENDERS = ['男', '女']

  ASTROS = [
    '白羊座',
    '金牛座',
    '双子座',
    '巨蟹座',
    '狮子座',
    '处女座',
    '天秤座',
    '天蝎座',
    '射手座',
    '摩羯座',
    '水瓶座',
    '双鱼座',
  ]

  validates_length_of :name, maximum: 10, on: :update
  validates_length_of :city, maximum: 10, on: :update
  validates_length_of :intro, maximum: 300, on: :update
  validates_inclusion_of :gender, in: GENDERS, allow_nil: true, on: :update
  validates_inclusion_of :astro, in: ASTROS, allow_nil: true, on: :update

  def likeables_with(klass, like_type)
    klass.where(id: Like.liked_by(self).where(likeable_type: klass.table_name.classify, like_type: like_type).select(:likeable_id))
  end

  def likes_with?(likeable, like_type)
    _like = Like.liked_by(self).liking(likeable).last
    _like.present? && _like.like_type == like_type
  end

  def like_with!(likeable, like_type)
    ActiveRecord::Base.transaction do
      self.like! likeable
      _like = Like.liked_by(self).liking(likeable).last
      _like.like_type = like_type
      raise ActiveRecord::Rollback if !_like.save
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]
  before_action :authenticate_user!, except: [:index, :show, :destroy]
  before_action :authenticate_admin!, only: [:index, :destroy]

  def index
    @users = User.where.not(id: current_user.id).order(id: :desc)
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def show
  end

  def messages
    if current_user.nil?
      flash[:error] = "请先登录。"
      redirect_to user_path(@user)
      return
    end
    msg = current_user.send_message(@user, { body: params[:content] })
    puts msg.to_json, msg.errors.to_json
    if msg.id.present?
      flash[:notice] = "消息已发送。"
    else
      flash[:error] = "无法发送消息。"
    end
    redirect_to user_path(@user)
  end

  def follow
    current_user.follow! @user
    flash[:notice] = "已关注用户。"
    redirect_to user_path(@user)
  end

  def unfollow
    current_user.unfollow! @user
    flash[:notice] = "已取消关注用户。"
    redirect_to user_path(@user)
  end

  private
    def set_user
      @user = User.find(params[:user_id] || params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2>用户列表</h2>

<hr>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>用户</th>
      <th>性别</th>
      <th>星座</th>
      <th>地区</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td>
          <%= link_to user do %>
            <%= image_tag user.avatar || 'user.png', width: 32, height: 32, class: 'user-avatar' %>
            <%= user.name || user.email %>
          <% end %>
        </td>
        <td><%= user.gender %></td>
        <td><%= user.astro %></td>
        <td><%= user.city %></td>
        <td><%= link_to '删除', user, method: :delete, data: { confirm: '确认删除？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="userpage">
      <div class="userpage-avatar">
        <%= image_tag @user.avatar || 'user.png', width: 100, height: 100 %>
      </div>
      <div class="userpage-info">
        <h2>
          <%= @user.name || @user.email %>
          <% if current_user && @user != current_user %>
            <% if current_user.follows?(@user) %>
              <%= link_to "取消关注", user_follows_path(@user), method: :delete, class: 'userpage-action' %>
            <% else %>
              <%= link_to "关注此用户", user_follows_path(@user), method: :post, class: 'userpage-action' %>
            <% end %>
            <%= link_to "发送消息", '#', data: { toggle: 'modal',  target: '#message' }, class: 'userpage-action' %>
          <% end %>
        </h2>
        <%= simple_format @user.intro %>
        <p><%= "#{@user.gender} #{@user.city} #{@user.astro}" %></p>
      </div>
    </div>
  </div>
</div>

<% wish_count = @user.likeables_with(Movie, 'wish').count %>
<% watched_count = @user.likeables_with(Movie, 'watched').count %>

<div class="row">
  <div class="col-sm-6">
    <ul class="nav nav-tabs">
      <li class="no-link"><a>想看的电影 (<%= wish_count %>)</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active">
        <% if wish_count == 0 %>
          <p class="user-none">当前没有想看的电影。</p>
        <% else %>
          <div class="user-movies">
            <% @user.likeables_with(Movie, 'wish').each do |movie| %>
              <%= link_to movie_path(movie), class: 'user-movie', data: { toggle: 'tooltip', placement: 'bottom', title: movie.name } do %>
                <%= image_tag movie.poster, width: 60, height: 90 %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <ul class="nav nav-tabs">
      <li class="no-link"><a>看过的电影 (<%= watched_count %>)</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active">
        <% if watched_count == 0 %>
          <p class="user-none">当前没有看过的电影。</p>
        <% else %>
          <div class="user-movies">
            <% @user.likeables_with(Movie, 'watched').each do |movie| %>
              <%= link_to movie_path(movie), class: 'user-movie', data: { toggle: 'tooltip', placement: 'bottom', title: movie.name } do %>
                <%= image_tag movie.poster, width: 60, height: 90 %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% followees_count = @user.followees(User).count %>
<% followers_count = @user.followers(User).count %>

<div class="row">
  <div class="col-sm-6">
    <ul class="nav nav-tabs">
      <li class="no-link"><a>已关注 (<%= followees_count %>)</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active">
        <% if followees_count == 0 %>
          <p class="user-none">当前没有关注任何人。</p>
        <% else %>
          <div class="user-follows">
            <% @user.followees(User).each do |user| %>
              <%= link_to user_path(user), class: 'user-follow', data: { toggle: 'tooltip', placement: 'bottom', title: user.name || user.email } do %>
                <%= image_tag user.avatar || 'user.png', width: 32, height: 32, class: 'user-avatar' %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <ul class="nav nav-tabs">
      <li class="no-link"><a>被关注 (<%= followers_count %>)</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active">
        <% if followers_count == 0 %>
          <p class="user-none">当前没有被任何人关注。</p>
        <% else %>
          <div class="user-follows">
            <% @user.followers(User).each do |user| %>
              <%= link_to user_path(user), class: 'user-follow', data: { toggle: 'tooltip', placement: 'bottom', title: user.name || user.email } do %>
                <%= image_tag user.avatar || 'user.png', width: 32, height: 32, class: 'user-avatar' %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
$(function () { $('[data-toggle="tooltip"]').tooltip(); });
</script>

<% if @user == current_user %>
  <% received_messages_count = current_user.received_messages.count %>
  <div class="row">
    <div class="col-sm-12">
      <ul class="nav nav-tabs">
        <li class="no-link"><a>我的消息 (<%= received_messages_count %>)</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active">
          <% if received_messages_count == 0 %>
            <p class="user-none">当前没有个人消息。</p>
          <% else %>
            <table class="table">
              <tbody>
                  <tr>
                    <th width="20%">发送日期</th>
                    <th width="20%">发件人</th>
                    <th width="60%">内容</th>
                  </tr>
              </tbody>
              <tbody>
                <% current_user.received_messages.each do |msg| %>
                  <tr>
                    <td><%= msg.created_at.strftime('%F %T') %></td>
                    <td><%= link_to msg.from.name || msg.from.email, user_path(msg.from) %></td>
                    <td>
                      <a href class="remove-hidden">显示</a>
                      <span style="display: none"><%= simple_format msg.body %></span>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <script>
    $('.remove-hidden').click(function (e) {
      e.preventDefault();
      $(this).next().show();
      $(this).remove();
    });
  </script>
<% end %>

<div class="modal fade" id="message" tabindex="-1">
  <div class="modal-dialog">
    <%= bootstrap_form_tag url: user_messages_path(@user) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
          <h4 class="modal-title">向 <%= @user.name || @user.email %> 发消息</h4>
        </div>
        <div class="modal-body">
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.text_area :content, label: "内容", rows: 5 %>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">发送</button>
        </div>
      </div>
    <% end %>
  </div>
</div>