config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:index, :show, :destroy] do
    post :follows, to: 'users#follow'
    delete :follows, to: 'users#unfollow'
    post :messages
  end
  resources :cinemas
  resources :movies do
    resources :timetables, except: [:show, :index]
    resources :photos, only: [:index, :update, :destroy]
    post :add_photos, on: :member, to: 'movies#add_photos'
    post :likes, on: :member, to: 'movies#like'
    delete :likes, on: :member, to: 'movies#unlike'
    post :comments, on: :member, to: 'movies#new_comment'
    patch :comments, on: :member, to: 'movies#new_comment'
    delete :comments, on: :member, to: 'movies#delete_comment'
    delete :comment_by_id, on: :member, to: 'movies#delete_comment_by_id'
    delete :timetables_by_cinema, on: :member, to: 'movies#delete_timetables_by_cinema'
  end
end

app/models/cinema.rb
class Cinema < ActiveRecord::Base
  has_many :movies, through: :timetables
  has_many :timetables

  scope :of_city, -> (city) { where('city': city) }
  scope :of_district, -> (city) { where('district': district) }

  validates_presence_of :name, message: '请输入影院名称'
  validates_presence_of :city, message: '请输入影院所在城市'
  validates_presence_of :content, message: '请输入影院介绍'

  def self.for_select(city)
    Cinema.of_city(city).select(:id, :name, :district).order(district: :desc, id: :asc).group_by(&:district).
      map { |key, val| ["#{key.presence || '其他'} (#{val.size})", val.map{ |cinema| [cinema.name, cinema.id] }] }.to_h
  end
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  before_action :set_cinema, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]

  # GET /cinemas
  def index
    @cinemas = Cinema.where(city: current_city)
    respond_to do |format|
      format.html
      format.json {
        if params[:district].present?
          @cinemas = @cinemas.where(district: params[:district])
        else
          @cinemas = @cinemas.
            select('cinemas.*, COUNT(timetables.id) AS ttcount').
            joins(:timetables).
            group('cinemas.id').
            order('ttcount DESC').
            limit(10)
        end
        render json: @cinemas.select(:id, :name).as_json.map { |cinema|
          cinema['link'] = cinema_path(cinema['id'])
          cinema
        }
      }
    end
  end

  # GET /cinemas/1
  def show
    @dates = @cinema.timetables.select(:date).uniq.where('date >= ?', Date.current).order(date: :asc).limit(7).pluck(:date)
  end

  # GET /cinemas/new
  def new
    @cinema = Cinema.new
  end

  # GET /cinemas/1/edit
  def edit
  end

  # POST /cinemas
  def create
    @cinema = Cinema.new(cinema_params)

    if @cinema.save
      redirect_to @cinema, notice: '影院已创建。'
    else
      render :new
    end
  end

  # PATCH/PUT /cinemas/1
  def update
    if @cinema.update(cinema_params)
      redirect_to @cinema, notice: '影院已修改。'
    else
      render :edit
    end
  end

  # DELETE /cinemas/1
  def destroy
    @cinema.destroy
    redirect_to cinemas_url, notice: '影院已删除。'
  end

  helper_method :price_tags

  def price_tags(prices_json)
    prices = JSON.parse(prices_json)
    tags = ''
    Timetable::PRICE_PROVIDERS.each do |name, display_name|
      value = prices[name.to_s]
      if value
        tags << view_context.content_tag(:div, class: 'movie-price') do
          (display_name + '：' + view_context.content_tag(:span, value, class: 'movie-price-number')).html_safe
        end
      end
    end
    tags.html_safe
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cinema
      @cinema = Cinema.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cinema_params
      permitted = params.require(:cinema).permit(:name, :logo, :logo_file, :city, :district, :content, :address, :phone, :business_hours)
      logo = upload_image(permitted['logo_file'], sub_dir = 'logos', resize = '102x44!>')
      permitted.delete('logo_file')
      permitted['logo'] = logo if logo
      permitted
    end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_form.html.erb
<%= bootstrap_form_for @cinema, layout: :horizontal do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :logo, placeholder: '输入网址或者直接上传标志' %>
  <%= f.file_field :logo_file, label: '上传标志' %>
  <%= f.text_field :city %>
  <%= f.text_field :district %>
  <%= f.text_field :address %>
  <%= f.text_field :phone %>
  <%= f.text_field :business_hours %>
  <%= f.text_area :content, rows: 10 %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/cinemas/edit.html.erb
<h2>编辑影院</h2>

<hr>

<div class="btn-group">
  <%= link_to '影院列表', cinemas_path, class: 'btn btn-sm btn-default' %>
  <%= link_to '影院页', @cinema, class: 'btn btn-sm btn-default' %>
</div>

<hr>

<%= render 'form' %>

app/views/cinemas/index.html.erb
<h2>影院列表</h2>

<hr>

<% if is_admin? %>
  <%= link_to '创建新影院', new_cinema_path, class: 'btn btn-sm btn-default' %>
  <hr>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>名称</th>
      <th>城市</th>
      <% if is_admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @cinemas.each do |cinema| %>
      <tr>
        <td><%= link_to cinema do %><%= image_tag cinema.logo, width: 102, height: 44 %><% end %></td>
        <td><%= link_to cinema.name, cinema %></td>
        <td><%= cinema.city %></td>
        <% if is_admin? %>
          <td><%= link_to '编辑', edit_cinema_path(cinema) %></td>
          <td><%= link_to '删除', cinema, method: :delete, data: { confirm: '确认删除？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cinemas/new.html.erb
<h2>创建新影院</h2>

<hr>

<%= link_to '影院列表', cinemas_path, class: 'btn btn-sm btn-default' %>

<hr>

<%= render 'form' %>

app/views/cinemas/show.html.erb
<div class="row cinema-header">
  <div class="col-sm-9">
    <div class="pull-left cinema-logo">
      <%= image_tag @cinema.logo, width: 102, height: 44 %>
    </div>
    <div class="pull-left">
      <h2 class="cinema-name">
        <%= @cinema.name %>
        <% if is_admin? %>
          <div class="btn-group">
            <%= link_to '新增影院', new_cinema_path(@cinema), class: 'btn btn-sm btn-default' %>
            <%= link_to '编辑影院', edit_cinema_path(@cinema), class: 'btn btn-sm btn-default' %>
            <%= link_to '删除影院', cinema_path(@cinema), data: { method: 'delete' }, class: 'btn btn-sm btn-default' %>
          </div>
        <% end %>
      </h2>
      <h5><%= @cinema.city %> <%= @cinema.district %></h5>
    </div>
  </div>
  <div class="col-sm-3 cinema-info">
    地址：<%= @cinema.address %><br>
    电话：<%= @cinema.phone %> 营业时间：<%= @cinema.business_hours %>
  </div>
</div>

<div class="row cinema-header">
  <div class="col-sm-9">
    <ul class="nav nav-tabs">
      <% @dates.each.with_index do |date, i| %>
        <li class="<%= i == 0 && ' active' || '' %>">
          <a href="#date-<%= date %>" data-toggle="tab">
            <%= date.strftime('%-m月%-d日') %>
          </a>
        </li>
      <% end %>
    </ul>

    <div class="tab-content cinema-list">
      <% @dates.each.with_index do |date, i| %>
        <div class="tab-pane<%= i == 0 && ' active' || '' %>" id="date-<%= date %>">

          <% movies = @cinema.timetables.where(date: date).group(:movie_id) %>

          <ul class="nav nav-tabs">
            <% movies.each.with_index do |tt, i| %>
              <li class="<%= i == 0 && ' active' || '' %>">
                <a href="#date-<%= date %>-<%= tt.movie.id %>" data-toggle="tab">
                  <%= image_tag tt.movie.poster, width: 100, height: 150 %>
                  <br>
                  <%= tt.movie.name %>
                </a>
              </li>
            <% end %>
          </ul>

          <div class="tab-content">
            <% movies.each.with_index do |tt, i| %>
              <div class="tab-pane<%= i == 0 && ' active' || '' %>" id="date-<%= date %>-<%= tt.movie.id %>">
                <h2>
                  <%= link_to tt.movie.name, tt.movie %>
                  <small>
                  <span class="label label-success"><%= tt.movie.ratings %></span>
                  </small>
                  <% if is_admin? %>
                    <%= link_to '创建新时间', new_movie_timetable_path(tt.movie), class: 'btn btn-sm btn-default' %>
                  <% end %>
                </h2>
                <table class="table cinema-timetable">
                  <tbody>
                    <% @cinema.timetables.where(date: date).where(movie: tt.movie.id).each.with_index do |t, i| %>
                      <tr>
                        <td class="ctt-1">
                          <h3><%= t.time.strftime('%H:%M') %></h3>
                          <% if not tt.movie.runtime.nil? %>
                            <span>预计<%= (t.time + tt.movie.runtime * 60).strftime('%H:%M') %>离场</span>
                          <% end %>
                        </td>
                        <td class="ctt-2">
                          <span>3D<br>中文</span>
                        </td>
                        <td class="ctt-3">
                          <span><%= t.room %></span>
                        </td>
                        <td class="ctt-4">
                          <%= price_tags t.prices %>
                          <% if is_admin? %>
                            <%= link_to '编辑', edit_movie_timetable_path(tt.movie, t) %>
                            <%= link_to '删除', movie_timetable_path(tt.movie, t), method: :delete %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>
  </div>
  <div class="col-sm-3">
    <h3>影院介绍</h3>
    <%= simple_format @cinema.content %>
  </div>
</div>