config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, only: [:index, :show, :destroy] do
    post :follows, to: 'users#follow'
    delete :follows, to: 'users#unfollow'
    post :messages
  end
  resources :cinemas
  resources :movies do
    resources :timetables, except: [:show, :index]
    resources :photos, only: [:index, :update, :destroy]
    post :add_photos, on: :member, to: 'movies#add_photos'
    post :likes, on: :member, to: 'movies#like'
    delete :likes, on: :member, to: 'movies#unlike'
    post :comments, on: :member, to: 'movies#new_comment'
    patch :comments, on: :member, to: 'movies#new_comment'
    delete :comments, on: :member, to: 'movies#delete_comment'
    delete :comment_by_id, on: :member, to: 'movies#delete_comment_by_id'
    delete :timetables_by_cinema, on: :member, to: 'movies#delete_timetables_by_cinema'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Buji</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:;base64,iVBORw0KGgo=">
<link href="//dn-staticfile.qbox.me/twitter-bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
<script src="//dn-staticfile.qbox.me/jquery/1.11.3/jquery.min.js"></script>
<script src="//dn-staticfile.qbox.me/jquery-ujs/1.1.0/rails.min.js"></script>
<script src="//dn-staticfile.qbox.me/twitter-bootstrap/3.2.0/js/bootstrap.min.js"></script>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header row">
      <div class="col-sm-4">
        <%= link_to root_path do %><%= image_tag 'logo.png', width: 108, height: 60 %><% end %>
        <a href class="select-city"><%= current_city %></a>
        <%= cities_list %>
        <script>
          $('.select-city').click(function (e) {
            e.preventDefault();
            $('.cities-list').toggleClass('open');
            $(this).blur();
          });
          $('.cities-list .close').click(function (e) {
            $('.cities-list').removeClass('open');
          });
          $('[data-select-key]').click(function (e) {
            e.preventDefault();
            var key = $(this).data('select-key');
            $('[data-select-key]').removeClass('active');
            $(this).addClass('active');
            $('[data-key').removeClass('active');
            $('[data-key="' + key + '"').addClass('active');
          });
        </script>
      </div><div class="header-search col-sm-4">
        <%= form_tag movies_path, method: :get do %>
          <div class="input-group">
            <input type="text" value="<%= params[:query] %>" name="query" class="form-control" placeholder="搜索电影">
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit">搜索</button>
            </span>
          </div>
        <% end %>
      </div><div class="text-right col-sm-4">
        <div class="btn-group">
          <% if user_signed_in? %>
            <%= link_to current_user.name.presence || current_user.email, user_path(current_user), class: 'btn header-link' %>
            <%= link_to "设置", edit_user_registration_path, class: 'btn header-link' %>
            <% if is_admin? %>
              <div class="btn-group header-admin-group" role="group">
                <button type="button" class="btn header-link dropdown-toggle" data-toggle="dropdown">
                  管理
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu pull-right">
                  <li><%= link_to "电影列表", movies_path %></li>
                  <li><%= link_to "新建电影", new_movie_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "影院列表", cinemas_path %></li>
                  <li><%= link_to "新建影院", new_cinema_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "用户列表", users_path %></li>
                </ul>
              </div>
            <% end %>
            <%= link_to '退出', destroy_user_session_path, method: :delete, class: 'btn header-link' %>
          <% else %>
            <%= link_to "登录", new_user_session_path, class: 'btn header-link' %>
            <%= link_to "注册", new_user_registration_path, class: 'btn header-link' %>
          <% end %>
        </div>
      </div>
    </div>
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
  <footer class="footer">
    <p class="footer-copy">&copy; 2016 buji</p>
  </footer>
</body>
</html>